### ISSUE TITLE
Spree 3.0.0 compatibility

### ISSUE THREAD

**Issue by leeknowlton** [nebulab/spree-subscriptions#68]
When trying to use this gem with Spree 3.0.0 the following error message appears

"Bundler could not find compatible versions for gem "spree":
  In Gemfile:
    spree_subscriptions (>= 0) ruby depends on
      spree (~> 2.4.4) ruby

    spree (= 3.0.0) ruby"

Are you planning on releasing an update?

**Comment by kennyadsl** [comment]
Hi @leeknowlton, I've updated the extension to be spree 3 compatible. 
Please, check out the 3-0-stable branch and let us know if you find any issue! :beers:

**Comment by leeknowlton** [comment]
Thanks! Will try it soon.

**Comment by leeknowlton** [comment]
There seem to be some CSS problems in the admin section with strange text sizes and squished tables (I haven't used previous version...it could have just been like this)

Pic 1
![capture2](https://cloud.githubusercontent.com/assets/2668502/7340421/7bb4f0de-ece1-11e4-8134-15bd50a6c98e.PNG)

Pic 2
![capture3](https://cloud.githubusercontent.com/assets/2668502/7340420/7bb3e6f8-ece1-11e4-8d21-7f5a37f9f9b6.PNG)

Pic 3
![capture](https://cloud.githubusercontent.com/assets/2668502/7340422/7bb5caae-ece1-11e4-872e-90c7278f43d6.PNG)

**Comment by kennyadsl** [comment]
@leeknowlton yes, I just let specs pass but haven't yet styled anything with new frontend and backend themes. I'll do it as soon as possible.

**Comment by kennyadsl** [comment]
@leeknowlton If you have time, I'd be happy to merge some PR on this. Thanks for reporting anyway!
