### ISSUE TITLE
2.4 compatible issue 

### ISSUE THREAD

**Issue by Qubaish** [nebulab/spree-subscriptions#69]
This gem is really helpful, i just want to know that is this gem is compatible with spree 2.4 because i am facing the issue when is start my bundler 

Bundler could not find compatible versions for gem "spree":
  In snapshot (Gemfile.lock):
    spree (= 2.4.3.beta)

  In Gemfile:
    spree_subscriptions (>= 0) ruby depends on
      spree (~> 2.4.4) ruby

```
spree (>= 0) ruby
```

Thanks

**Comment by kennyadsl** [comment]
hi @Qubaish, thanks for reporting this issue. It seems like you are using the 2.4.3.beta version of spree. I think that updating the spree gem it will allow to use this extension. Try running:

`bundle update --source spree`

**Comment by Qubaish** [comment]
Hi thanks for the quick response, i try to run this command but it also gives error 

Bundler could not find compatible versions for gem "spree_core":
  In snapshot (Gemfile.lock):
    spree_core (= 2.4.3.beta)

  In Gemfile:
    spree_core (~> 2.4.0) ruby

```
spree (>= 0) ruby depends on
  spree_core (= 2.4.8.beta) ruby
```

Here is my gem file 

gem 'spree', github: 'spree/spree', branch: '2-4-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '2-4-stable'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '2-4-stable'
gem 'spree_paypal_express', github: 'spree-contrib/better_spree_paypal_express'
gem 'spree_editor', github: 'spree-contrib/spree_editor', branch: '2-4-stable'
gem 'spree_subscriptions', github: 'nebulab/spree-subscriptions', branch: '2-4-stable'

Thanks

**Comment by kennyadsl** [comment]
You should look in your Gemfile.lock and understand which gem is locking spree_core gem to that particular version (2.4.3)

**Comment by Qubaish** [comment]
I appreciate your help, spree paypal caused that problem now i solved it.

Thanks

**Comment by kennyadsl** [comment]
@Qubaish happy you solved! :beers:
